language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO_FUTURE_VERSION=1.5 DJANGO_SETTINGS_MODULE=easy_thumbnails.tests.settings_old
  - DJANGO_FUTURE_VERSION=1.6 DJANGO_SETTINGS_MODULE=easy_thumbnails.tests.settings_old
  - DJANGO_FUTURE_VERSION=1.7 DJANGO_SETTINGS_MODULE=easy_thumbnails.tests.settings

install:
  - pip install --use-mirrors "Django<$DJANGO_FUTURE_VERSION" testfixtures django-discover-runner
  - pip install --use-mirrors .

script:
  - django-admin.py test --traceback

matrix:
  exclude:
    - env: DJANGO_FUTURE_VERSION=1.5 DJANGO_SETTINGS_MODULE=easy_thumbnails.tests.settings_old
      python: "3.3"
